### ISSUE TITLE
CompileError when using latest binaryen.js and running in node

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#2116]
When compiling with latest binaryen.js (84.0.0-nightly.20190517 based on 1dd37de) and running the resulting module with node, I get the following error:

```
CompileError: WebAssembly.Module(): Wasm decoding failed: unexpected section: Code @+260
```

Might this have something to do with [all features being enabled by default](https://github.com/WebAssembly/binaryen/blob/master/src/binaryen-c.cpp#L3108) / some feature implicitly adding a new section that node doesn't like? Looking through the issues, it seems something similar happend with the DataCount section [a while ago](https://github.com/WebAssembly/binaryen/pull/2010).

**Comment by tlively** [comment]
Can you wasm-objdump (from WABT) the module and report what kind of sections it contains?

**Comment by dcodeIO** [comment]
Output is:

```
simd.untouched.wasm:    file format wasm 0x1

Section Details:

Type[2]:
 - type[0] () -> nil
 - type[1] (i32, i32, i32, i32) -> nil
Import[1]:
 - func[0] sig=1 <~lib/builtins/abort> <- env.abort
Function[11]:
 - func[1] sig=0 <simd/test_v128>
 - func[2] sig=0 <simd/test_i8x16>
 - func[3] sig=0 <simd/test_i16x8>
 - func[4] sig=0 <simd/test_i32x4>
 - func[5] sig=0 <simd/test_i64x2>
 - func[6] sig=0 <simd/test_f32x4>
 - func[7] sig=0 <simd/test_f64x2>
 - func[8] sig=0 <simd/test_v8x16>
 - func[9] sig=0 <start:simd>
 - func[10] sig=0 <start>
 - func[11] sig=0 <null>
Table[1]:
 - table[0] type=funcref initial=1
Memory[1]:
 - memory[0] pages: initial=1
Global[1]:
 - global[0] i32 mutable=0 - init i32=0
Export[1]:
 - memory[0] -> "memory"
Start:
 - start function: 10
Elem[1]:
 - segment[0] table=0 count=1 - init i32=0
  - elem[0] = func[11] <null>
Code[11]:
 - func[1] size=508 <simd/test_v128>
 - func[2] size=1197 <simd/test_i8x16>
 - func[3] size=1205 <simd/test_i16x8>
 - func[4] size=1032 <simd/test_i32x4>
 - func[5] size=685 <simd/test_i64x2>
 - func[6] size=1012 <simd/test_f32x4>
 - func[7] size=1052 <simd/test_f64x2>
 - func[8] size=107 <simd/test_v8x16>
 - func[9] size=18 <start:simd>
 - func[10] size=4 <start>
 - func[11] size=2 <null>
Data[1]:
 - segment[0] size=30 - init i32=8
  - 0000008: 0e00 0000 0100 0000 1100 0000 0e00 0000  ................
  - 0000018: 7300 6900 6d00 6400 2e00 7400 7300       s.i.m.d...t.s.
Custom:
 - name: "name"
 - func[0] <~lib/builtins/abort>
 - func[1] <simd/test_v128>
 - func[2] <simd/test_i8x16>
 - func[3] <simd/test_i16x8>
 - func[4] <simd/test_i32x4>
 - func[5] <simd/test_i64x2>
 - func[6] <simd/test_f32x4>
 - func[7] <simd/test_f64x2>
 - func[8] <simd/test_v8x16>
 - func[9] <start:simd>
 - func[10] <start>
 - func[11] <null>
```
